# Site settings
title: Cosma Cat Home Page
timezone: Europe/Moscow # временная зона
encoding: UTF-8
baseurl: ""
url: http://cosmacat.ru

# Build settings
markdown: kramdown

# Defaults
defaults:
  -
    scope:
      type: "pages"
    values:
      menu: false